import type { FormField } from "@/types";

export interface FormTemplate {
  id: string;
  title: string;
  description: string;
  phase: "pre-visit" | "during-visit" | "post-visit" | "network";
  target_role: "enrollment_user" | "volunteer" | "admin" | "all";
  fields: FormField[];
}

export const FORM_TEMPLATES: FormTemplate[] = [
  // Pre-Visit
  {
    id: "demo-feedback",
    title: "Demo Session Observation & Feedback",
    description: "Feedback form for demo sessions conducted in nearby schools during training",
    phase: "pre-visit",
    target_role: "volunteer",
    fields: [
      { id: "school_name", type: "text", label: "School Name", required: true },
      { id: "date", type: "date", label: "Date of Demo", required: true },
      { id: "class_observed", type: "text", label: "Class / Grade Observed", required: true },
      { id: "activity_conducted", type: "textarea", label: "Activity Conducted", required: true },
      { id: "student_response", type: "textarea", label: "Student Response & Engagement", required: true },
      { id: "strengths", type: "textarea", label: "Strengths Observed" },
      { id: "improvements", type: "textarea", label: "Areas for Improvement" },
      { id: "overall_rating", type: "radio", label: "Overall Rating", required: true, options: ["Excellent", "Good", "Average", "Needs Work"] },
      { id: "mentor_remarks", type: "textarea", label: "Remarks by Experienced Volunteer / Mentor" },
    ],
  },
  {
    id: "state-study",
    title: "State Study Template",
    description: "Structured background research template for the allocated state",
    phase: "pre-visit",
    target_role: "volunteer",
    fields: [
      { id: "state_name", type: "text", label: "State Name", required: true },
      { id: "geography", type: "textarea", label: "Geography & Climate", required: true },
      { id: "culture_language", type: "textarea", label: "Culture, Language & Traditions", required: true },
      { id: "education_system", type: "textarea", label: "Education System & Challenges" },
      { id: "key_festivals", type: "textarea", label: "Key Festivals & Celebrations" },
      { id: "social_issues", type: "textarea", label: "Social Issues & Context" },
      { id: "food_customs", type: "textarea", label: "Food & Daily Customs" },
      { id: "notable_personalities", type: "textarea", label: "Notable Personalities & Role Models" },
      { id: "key_learnings", type: "textarea", label: "Key Learnings for Workshop Design", required: true },
      { id: "sources", type: "textarea", label: "Sources & References" },
    ],
  },
  {
    id: "workshop-planning",
    title: "Workshop Planning Sheet",
    description: "Workshop design and session flow planning document",
    phase: "pre-visit",
    target_role: "volunteer",
    fields: [
      { id: "workshop_title", type: "text", label: "Workshop / Session Title", required: true },
      { id: "target_audience", type: "text", label: "Target Audience (age / class)", required: true },
      { id: "duration", type: "text", label: "Duration", required: true },
      { id: "objectives", type: "textarea", label: "Learning Objectives", required: true },
      { id: "materials_needed", type: "textarea", label: "Materials Needed" },
      { id: "session_flow", type: "textarea", label: "Session Flow / Activity Plan", required: true },
      { id: "cultural_elements", type: "textarea", label: "Cultural Exchange Elements (Rangoli, Mehendi, Songs, etc.)" },
      { id: "contingency", type: "textarea", label: "Contingency Plan (if things go off-track)" },
    ],
  },
  {
    id: "role-allocation",
    title: "Responsibility & Role Allocation Sheet",
    description: "Record of volunteer roles and responsibilities for the visit",
    phase: "pre-visit",
    target_role: "volunteer",
    fields: [
      { id: "volunteer_name", type: "text", label: "Volunteer Name", required: true },
      { id: "primary_role", type: "select", label: "Primary Role", required: true, options: ["Team Leader", "Workshop Lead", "Documentation Lead", "Cultural Activities Lead", "Logistics Coordinator", "Photography & Media", "Community Liaison", "Report Writing Lead", "General Volunteer"] },
      { id: "specific_tasks", type: "textarea", label: "Specific Tasks & Responsibilities", required: true },
      { id: "sessions_assigned", type: "textarea", label: "Sessions / Activities Assigned" },
      { id: "backup_role", type: "text", label: "Backup Role (if primary unavailable)" },
      { id: "special_skills", type: "textarea", label: "Special Skills Being Utilized" },
    ],
  },
  // During Visit
  {
    id: "daily-activity-plan",
    title: "Daily Activity Planning Sheet",
    description: "Plan for the day's activities before field execution",
    phase: "during-visit",
    target_role: "volunteer",
    fields: [
      { id: "date", type: "date", label: "Date", required: true },
      { id: "location", type: "text", label: "School / Community / Location", required: true },
      { id: "schedule", type: "textarea", label: "Time-wise Schedule", required: true },
      { id: "responsible_volunteers", type: "textarea", label: "Responsible Volunteers per Activity", required: true },
      { id: "materials_ready", type: "checkbox", label: "Materials Ready?", options: ["All materials confirmed and packed"] },
      { id: "special_notes", type: "textarea", label: "Special Instructions / Notes" },
    ],
  },
  {
    id: "workshop-documentation",
    title: "Workshop Documentation Sheet",
    description: "Record of workshop conducted during school / community visit",
    phase: "during-visit",
    target_role: "volunteer",
    fields: [
      { id: "date", type: "date", label: "Date", required: true },
      { id: "school_name", type: "text", label: "School / Community Name", required: true },
      { id: "location", type: "text", label: "Location / Address", required: true },
      { id: "class_grade", type: "text", label: "Class / Grade / Audience", required: true },
      { id: "number_students", type: "number", label: "Number of Students / Participants", required: true },
      { id: "teachers_present", type: "number", label: "Teachers Present" },
      { id: "sessions_conducted", type: "textarea", label: "Sessions / Activities Conducted", required: true },
      { id: "student_engagement", type: "radio", label: "Student Engagement Level", required: true, options: ["Very High", "High", "Moderate", "Low"] },
      { id: "highlights", type: "textarea", label: "Highlights & Memorable Moments", required: true },
      { id: "challenges", type: "textarea", label: "Challenges Faced" },
      { id: "volunteer_notes", type: "textarea", label: "Volunteer Observations" },
    ],
  },
  {
    id: "school-visit-record",
    title: "School Visit Record",
    description: "Structured record for each school or institution visited",
    phase: "during-visit",
    target_role: "volunteer",
    fields: [
      { id: "date", type: "date", label: "Visit Date", required: true },
      { id: "school_name", type: "text", label: "School Name", required: true },
      { id: "principal_name", type: "text", label: "Principal / Head Teacher Name" },
      { id: "contact_number", type: "text", label: "Contact Number" },
      { id: "address", type: "textarea", label: "School Address" },
      { id: "medium_of_instruction", type: "select", label: "Medium of Instruction", options: ["Hindi", "English", "Regional Language", "Mixed"] },
      { id: "total_students", type: "number", label: "Total Enrolled Students" },
      { id: "classes_engaged", type: "text", label: "Classes / Grades Engaged" },
      { id: "activities_done", type: "textarea", label: "Activities Done", required: true },
      { id: "school_response", type: "radio", label: "School's Response & Receptiveness", required: true, options: ["Very Welcoming", "Welcoming", "Neutral", "Reluctant"] },
      { id: "follow_up", type: "textarea", label: "Follow-up Required?" },
      { id: "photo_taken", type: "checkbox", label: "Documentation", options: ["Photos taken", "Video recorded", "Written notes completed"] },
    ],
  },
  {
    id: "interaction-notes",
    title: "Interaction Notes",
    description: "Notes from interactions with teachers, community members, officials and social workers",
    phase: "during-visit",
    target_role: "volunteer",
    fields: [
      { id: "date", type: "date", label: "Date", required: true },
      { id: "person_name", type: "text", label: "Person Name", required: true },
      { id: "designation", type: "text", label: "Designation / Role", required: true },
      { id: "interaction_type", type: "select", label: "Type of Interaction", required: true, options: ["Teacher", "Principal", "Community Member", "Social Worker", "Government Official", "Parent", "Student", "Other"] },
      { id: "key_points", type: "textarea", label: "Key Points Discussed", required: true },
      { id: "insights", type: "textarea", label: "Insights & Learnings from Interaction" },
      { id: "action_points", type: "textarea", label: "Action Points / Follow-up" },
      { id: "contact_info", type: "text", label: "Contact Information (if shared)" },
    ],
  },
  // Post-Visit
  {
    id: "post-visit-feedback",
    title: "Post-Visit Feedback Form",
    description: "Volunteer reflection and feedback after returning from the visit",
    phase: "post-visit",
    target_role: "volunteer",
    fields: [
      { id: "overall_experience", type: "radio", label: "Overall Visit Experience", required: true, options: ["Excellent", "Very Good", "Good", "Average", "Below Expectations"] },
      { id: "most_impactful", type: "textarea", label: "Most Impactful Moment / Experience", required: true },
      { id: "personal_growth", type: "textarea", label: "What did you learn about yourself?", required: true },
      { id: "community_impact", type: "textarea", label: "What impact do you feel you made on the community?", required: true },
      { id: "challenges_faced", type: "textarea", label: "Challenges Faced & How You Overcame Them" },
      { id: "team_dynamics", type: "radio", label: "Team Collaboration & Dynamics", options: ["Excellent", "Good", "Average", "Needs Improvement"] },
      { id: "training_adequacy", type: "radio", label: "Was pre-visit training adequate?", options: ["Yes, fully prepared", "Mostly yes", "Somewhat", "No, more training needed"] },
      { id: "suggestions", type: "textarea", label: "Suggestions for Future Visits", required: true },
      { id: "would_volunteer_again", type: "radio", label: "Would you volunteer again?", required: true, options: ["Definitely Yes", "Probably Yes", "Unsure", "No"] },
      { id: "recommend_to_others", type: "radio", label: "Would you recommend Gyan Setu to others?", required: true, options: ["Definitely", "Probably", "Unsure", "No"] },
    ],
  },
  {
    id: "final-report",
    title: "Final Visit Report Submission",
    description: "Comprehensive final report of the visit by the team/group",
    phase: "post-visit",
    target_role: "volunteer",
    fields: [
      { id: "team_name", type: "text", label: "Team / Group Name", required: true },
      { id: "state_visited", type: "text", label: "State Visited", required: true },
      { id: "visit_dates", type: "text", label: "Visit Dates (from - to)", required: true },
      { id: "schools_visited", type: "number", label: "Number of Schools Visited", required: true },
      { id: "communities_engaged", type: "number", label: "Communities / Locations Engaged" },
      { id: "total_students_reached", type: "number", label: "Total Students Reached", required: true },
      { id: "total_teachers_met", type: "number", label: "Teachers / Staff Met" },
      { id: "workshops_conducted", type: "number", label: "Workshops Conducted", required: true },
      { id: "executive_summary", type: "textarea", label: "Executive Summary", required: true },
      { id: "key_achievements", type: "textarea", label: "Key Achievements", required: true },
      { id: "cultural_exchanges", type: "textarea", label: "Cultural Exchange Activities Conducted", required: true },
      { id: "challenges_solutions", type: "textarea", label: "Challenges & Solutions" },
      { id: "community_feedback", type: "textarea", label: "Community / School Feedback Received" },
      { id: "recommendations", type: "textarea", label: "Recommendations for Next Batch", required: true },
    ],
  },
  {
    id: "experience-sharing",
    title: "Experience Sharing Submission",
    description: "Volunteer's personal experience story to share with the next batch",
    phase: "post-visit",
    target_role: "volunteer",
    fields: [
      { id: "state_visited", type: "text", label: "State Visited", required: true },
      { id: "year", type: "text", label: "Year of Visit", required: true },
      { id: "story_title", type: "text", label: "Story / Experience Title", required: true },
      { id: "story", type: "textarea", label: "Your Story (in your own words)", required: true, placeholder: "Share a meaningful moment, interaction or transformation from your Gyan Setu journey..." },
      { id: "advice_to_next_batch", type: "textarea", label: "Advice to the Next Batch", required: true },
      { id: "quote", type: "text", label: "One Quote / Takeaway from your Experience" },
      { id: "permission_to_share", type: "radio", label: "Permission to share this story with future volunteers?", required: true, options: ["Yes, with my name", "Yes, anonymously", "No"] },
    ],
  },
  {
    id: "softboard-format",
    title: "Softboard Preparation Format",
    description: "Guide and checklist for preparing the visit softboard display",
    phase: "post-visit",
    target_role: "volunteer",
    fields: [
      { id: "team_name", type: "text", label: "Team / Group Name", required: true },
      { id: "state_name", type: "text", label: "State Name", required: true },
      { id: "title_banner", type: "text", label: "Title / Banner Text", required: true },
      { id: "sections_planned", type: "checkbox", label: "Sections to Include", required: true, options: ["State Introduction", "Team Members", "Schools Visited", "Workshop Photos", "Student Interactions", "Cultural Exchange", "Impact Numbers", "Quotes & Reflections", "Map"] },
      { id: "photos_selected", type: "number", label: "Number of Photos Selected" },
      { id: "layout_description", type: "textarea", label: "Layout Description", required: true },
      { id: "key_statistics", type: "textarea", label: "Key Statistics to Highlight", required: true },
      { id: "special_elements", type: "textarea", label: "Special Elements (local art, artifacts, drawings)" },
    ],
  },
  {
    id: "state-presentation",
    title: "State Presentation Preparation",
    description: "Structure and outline for the state presentation at Melawa/Katta",
    phase: "post-visit",
    target_role: "volunteer",
    fields: [
      { id: "team_name", type: "text", label: "Team Name", required: true },
      { id: "state_name", type: "text", label: "State Presented", required: true },
      { id: "presentation_date", type: "date", label: "Presentation Date" },
      { id: "duration_minutes", type: "number", label: "Allocated Duration (minutes)" },
      { id: "presenters", type: "textarea", label: "Presenters / Roles in Presentation", required: true },
      { id: "structure", type: "textarea", label: "Presentation Structure / Outline", required: true, placeholder: "1. Introduction (2 min)\n2. State Overview (3 min)\n3. School Visits (5 min)..." },
      { id: "key_stories", type: "textarea", label: "Key Stories to Share", required: true },
      { id: "av_requirements", type: "textarea", label: "AV / Tech Requirements" },
      { id: "cultural_performance", type: "textarea", label: "Cultural Performance Elements (if any)" },
    ],
  },
  // Network
  {
    id: "future-visit-interest",
    title: "Future Visit Interest & Participation Form",
    description: "Expression of interest in volunteering for future Gyan Setu visits",
    phase: "network",
    target_role: "all",
    fields: [
      { id: "full_name", type: "text", label: "Full Name", required: true },
      { id: "email", type: "text", label: "Email", required: true },
      { id: "phone", type: "text", label: "Phone Number", required: true },
      { id: "institution", type: "text", label: "College / Institution" },
      { id: "year_of_study", type: "text", label: "Year of Study / Occupation" },
      { id: "previous_gyan_setu", type: "radio", label: "Previous Gyan Setu Experience?", required: true, options: ["Yes - as Volunteer", "Yes - as Participant", "No - First time"] },
      { id: "states_willing", type: "textarea", label: "States You Would Like to Visit" },
      { id: "availability", type: "radio", label: "Availability", required: true, options: ["Summer vacation", "Winter vacation", "Flexible", "Only specific dates"] },
      { id: "special_skills", type: "textarea", label: "Special Skills / Strengths You Bring" },
      { id: "why_join", type: "textarea", label: "Why do you want to join Gyan Setu?", required: true },
      { id: "how_heard", type: "select", label: "How did you hear about Gyan Setu?", options: ["Friend / Volunteer", "Social Media", "College Notice", "Event / Presentation", "Other"] },
    ],
  },
];

export const PHASE_LABELS: Record<FormTemplate["phase"], string> = {
  "pre-visit": "Pre-Visit",
  "during-visit": "During Visit",
  "post-visit": "Post-Visit",
  "network": "Network",
};
