export const STATE_CITIES: Record<string, string[]> = {
  "Andhra Pradesh": ["Visakhapatnam","Vijayawada","Guntur","Nellore","Kurnool","Rajahmundry","Tirupati","Kakinada","Kadapa","Anantapur","Vizianagaram","Eluru","Ongole","Nandyal","Machilipatnam","Adoni","Tenali","Chittoor","Hindupur","Proddatur","Bhimavaram","Madanapalle","Guntakal","Dharmavaram","Tadepalligudem","Other"],
  "Arunachal Pradesh": ["Itanagar","Naharlagun","Pasighat","Namsai","Bomdila","Ziro","Along","Tezu","Roing","Tawang","Other"],
  "Assam": ["Guwahati","Silchar","Dibrugarh","Jorhat","Nagaon","Tinsukia","Tezpur","Bongaigaon","Dhubri","North Lakhimpur","Diphu","Karimganj","Sivasagar","Goalpara","Barpeta","Kokrajhar","Haflong","Other"],
  "Bihar": ["Patna","Gaya","Bhagalpur","Muzaffarpur","Purnia","Darbhanga","Arrah","Bihar Sharif","Begusarai","Katihar","Munger","Chapra","Hajipur","Sitamarhi","Motihari","Bettiah","Samastipur","Jehanabad","Nawada","Sasaram","Siwan","Dehri","Supaul","Other"],
  "Chhattisgarh": ["Raipur","Bhilai","Bilaspur","Korba","Durg","Rajnandgaon","Jagdalpur","Raigarh","Ambikapur","Dhamtari","Mahasamund","Kanker","Kondagaon","Other"],
  "Goa": ["Panaji","Margao","Vasco da Gama","Mapusa","Ponda","Bicholim","Curchorem","Sanquelim","Other"],
  "Gujarat": ["Ahmedabad","Surat","Vadodara","Rajkot","Bhavnagar","Jamnagar","Junagadh","Gandhinagar","Anand","Navsari","Morbi","Surendranagar","Bharuch","Mehsana","Bhuj","Porbandar","Palanpur","Valsad","Godhra","Nadiad","Amreli","Botad","Dahod","Other"],
  "Haryana": ["Faridabad","Gurugram","Panipat","Ambala","Yamunanagar","Rohtak","Hisar","Karnal","Sonipat","Panchkula","Bhiwani","Sirsa","Bahadurgarh","Jind","Thanesar","Kaithal","Palwal","Rewari","Fatehabad","Mahendragarh","Other"],
  "Himachal Pradesh": ["Shimla","Dharamshala","Solan","Mandi","Palampur","Baddi","Nahan","Kullu","Una","Chamba","Hamirpur","Bilaspur","Rampur","Sundernagar","Manali","Other"],
  "Jharkhand": ["Ranchi","Jamshedpur","Dhanbad","Bokaro","Deoghar","Hazaribagh","Giridih","Ramgarh","Phusro","Medininagar","Chaibasa","Chatra","Dumka","Pakur","Other"],
  "Karnataka": ["Bengaluru","Mysuru","Mangaluru","Belagavi","Kalaburagi","Ballari","Vijayapura","Shivamogga","Tumkuru","Davanagere","Bidar","Udupi","Dharwad","Raichur","Hassan","Hubli","Bagalkot","Mandya","Chitradurga","Koppal","Gadag","Yadgir","Other"],
  "Kerala": ["Thiruvananthapuram","Kochi","Kozhikode","Thrissur","Kollam","Palakkad","Alappuzha","Malappuram","Kannur","Kottayam","Kasaragod","Idukki","Pathanamthitta","Ponnani","Munnar","Other"],
  "Madhya Pradesh": ["Bhopal","Indore","Jabalpur","Gwalior","Ujjain","Sagar","Dewas","Satna","Ratlam","Rewa","Singrauli","Burhanpur","Khandwa","Bhind","Chhindwara","Guna","Shivpuri","Vidisha","Chhatarpur","Damoh","Mandsaur","Morena","Neemuch","Other"],
  "Maharashtra": ["Mumbai","Pune","Nagpur","Nashik","Aurangabad","Solapur","Kolhapur","Amravati","Nanded","Sangli","Jalgaon","Akola","Latur","Dhule","Ahmednagar","Chandrapur","Parbhani","Ichalkaranji","Jalna","Bhiwandi","Malegaon","Navi Mumbai","Thane","Vasai-Virar","Kalyan-Dombivali","Ulhasnagar","Panvel","Satara","Osmanabad","Wardha","Yavatmal","Buldhana","Washim","Hingoli","Gondia","Bhandara","Gadchiroli","Sindhudurg","Ratnagiri","Raigad","Other"],
  "Manipur": ["Imphal","Thoubal","Bishnupur","Churachandpur","Kakching","Ukhrul","Senapati","Tamenglong","Jiribam","Other"],
  "Meghalaya": ["Shillong","Tura","Jowai","Nongstoin","Williamnagar","Baghmara","Resubelpara","Other"],
  "Mizoram": ["Aizawl","Lunglei","Saiha","Champhai","Serchhip","Kolasib","Lawngtlai","Mamit","Other"],
  "Nagaland": ["Kohima","Dimapur","Mokokchung","Tuensang","Wokha","Zunheboto","Mon","Phek","Other"],
  "Odisha": ["Bhubaneswar","Cuttack","Rourkela","Berhampur","Sambalpur","Puri","Balasore","Bhadrak","Baripada","Jharsuguda","Jeypore","Bargarh","Angul","Dhenkanal","Kendujhar","Sundargarh","Other"],
  "Punjab": ["Ludhiana","Amritsar","Jalandhar","Patiala","Bathinda","Hoshiarpur","Mohali","Pathankot","Firozpur","Moga","Gurdaspur","Abohar","Ropar","Sangrur","Fatehgarh Sahib","Fazilka","Other"],
  "Rajasthan": ["Jaipur","Jodhpur","Kota","Bikaner","Ajmer","Udaipur","Bhilwara","Alwar","Bharatpur","Sikar","Pali","Sri Ganganagar","Nagaur","Barmer","Jhunjhunu","Tonk","Beawar","Hanumangarh","Churu","Kishangarh","Baran","Dhaulpur","Bundi","Other"],
  "Sikkim": ["Gangtok","Namchi","Geyzing","Mangan","Ravangla","Jorethang","Other"],
  "Tamil Nadu": ["Chennai","Coimbatore","Madurai","Tiruchirappalli","Salem","Tirunelveli","Tiruppur","Vellore","Erode","Thoothukkudi","Dindigul","Thanjavur","Kanchipuram","Cuddalore","Nagercoil","Kumbakonam","Hosur","Karur","Udhagamandalam","Nagapattinam","Other"],
  "Telangana": ["Hyderabad","Warangal","Nizamabad","Karimnagar","Khammam","Ramagundam","Mahbubnagar","Nalgonda","Adilabad","Suryapet","Miryalaguda","Siddipet","Jagtial","Mancherial","Bhongir","Other"],
  "Tripura": ["Agartala","Dharmanagar","Udaipur","Kailashahar","Belonia","Ambassa","Sabroom","Other"],
  "Uttar Pradesh": ["Lucknow","Kanpur","Ghaziabad","Agra","Meerut","Varanasi","Prayagraj","Bareilly","Aligarh","Moradabad","Saharanpur","Gorakhpur","Noida","Firozabad","Jhansi","Muzaffarnagar","Mathura","Rampur","Shahjahanpur","Mau","Farrukhabad","Hapur","Etawah","Mirzapur","Bulandshahr","Sambhal","Amroha","Hardoi","Azamgarh","Sitapur","Lakhimpur","Other"],
  "Uttarakhand": ["Dehradun","Haridwar","Rishikesh","Nainital","Roorkee","Haldwani","Rudrapur","Kashipur","Kotdwar","Pithoragarh","Almora","Ramnagar","Mussoorie","Tehri","Other"],
  "West Bengal": ["Kolkata","Howrah","Asansol","Siliguri","Durgapur","Bardhaman","Malda","Baranagar","Kharagpur","Haldia","Raiganj","Krishnanagar","Habra","Kalyani","Jalpaiguri","Darjeeling","Cooch Behar","Purulia","Bankura","Medinipur","Other"],
  "Delhi": ["New Delhi","North Delhi","South Delhi","East Delhi","West Delhi","Central Delhi","Dwarka","Rohini","Janakpuri","Lajpat Nagar","Saket","Other"],
  "Jammu & Kashmir": ["Srinagar","Jammu","Anantnag","Sopore","Baramulla","Kupwara","Pulwama","Udhampur","Kathua","Rajouri","Punch","Doda","Kishtwar","Other"],
  "Ladakh": ["Leh","Kargil","Nubra","Zanskar","Other"],
  "Chandigarh": ["Chandigarh","Other"],
  "Puducherry": ["Puducherry","Karaikal","Mahe","Yanam","Other"],
  "Other": ["Other"],
};

export const INDIAN_STATES = Object.keys(STATE_CITIES);
